TODOList/Models/DayModel.cs
using TODOList.services;

namespace TODOList.Models
{
    public class DayModel
    {
        public System.DayOfWeek Name { get; set; }
        public DateOnly Date { get; set; }
        public List<TaskModel>? Tasks { get; set; }


        public DayModel(DateOnly day)
        {
            Date = new DateOnly(day.Year, day.Month, day.Day);
            Name = Date.DayOfWeek;

            TasksDAO taskDAO = new();
            Tasks = (taskDAO.GetAllTasksForDay(Date));
            
        }
    }
}

TODOList/Models/ErrorViewModel.cs
namespace TODOList.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TODOList/Models/TaskModel.cs
using System.ComponentModel.DataAnnotations;

namespace TODOList.Models
{
    public class TaskModel
    {
        public int Id { set; get; }
        [Required]
        public string Name { set; get; }
        [Display(Name = "is done ?")]
        public bool IsDone { set; get; }
        public DateOnly Date { set; get; }
        public string? Priority { set; get; }
        public bool Regularity { set; get; }
        [DataType(DataType.Time)]
        //[DisplayFormat (DataFormatString = "{HH:mm}")]
        public TimeSpan StartTime { set; get; }
        [DataType(DataType.Time)]
        public TimeSpan EndTime { set; get; }
        public string? Description { set; get; }

    }
}

TODOList/Controllers/DayController.cs
using Microsoft.AspNetCore.Mvc;
using TODOList.Models;
using TODOList.services;

namespace TODOList.Controllers
{
    public class DayController : Controller
    {
        public IActionResult Index()
        {
            DateTime today = DateTime.Now;
            DateOnly dateOnlyToday = DateOnly.FromDateTime(today);

            List<DayModel> daysList = new();

            for (int i = 0; i < 7; i++)
            {
                var calcDay = dateOnlyToday.AddDays(i);

                daysList.Add(new DayModel(calcDay));
            }

            return View(daysList);
        }
        
        public IActionResult MarkAsDone(int Id)
        {
            TasksDAO taskDAO = new();
            TaskModel task = taskDAO.GetTask(Id);

            task.IsDone = true;
          
            taskDAO.Update(task);

            return PartialView("DoneTask", task);
        }

        /*
        public IActionResult DetailsTask(int Id)
        {
            TasksDAO taskDAO = new();
            //TaskModel task = new();
            TaskModel task = taskDAO.GetTask(Id);

            string page;
            if (task.IsDone == true)
                page = "DoneTask";
            else
                page = "DetailsTask";

            return PartialView(page, task);
        } */



    }
}

TODOList/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TODOList.Models;

namespace TODOList.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TODOList/Views/Day/DetailsTask.cshtml
@model TODOList.Models.TaskModel

<div class="navbar navbar-expand-lg navbar-light bg-light">
     
        <div class="card-header">
         <blockquote class="blockquote">&emsp; @Html.DisplayFor(model => model.Name)</blockquote>
         @Html.DisplayFor(model => model.StartTime) : @Html.DisplayFor(model => model.EndTime) &emsp;
         @Html.DisplayNameFor(model => model.Priority):  @Html.DisplayFor(model => model.Priority) &emsp;
         

        <form asp-action="MarkAsDone" asp-controller="Day">
        <input  class="TaskRadio" type="checkbox" name="Id" id="@Model.Id" value="@Model.Id"/>
            <label>
                @Html.DisplayNameFor(model => model.IsDone)
             </label> &emsp;

        </form>
        </div>

           <br> <br>
        <div style="clear:both;">
        <div class="card-text">
            @Html.DisplayFor(model => model.Description)
        </div>
        <br><br>

        <button type="button" class="btn btn-outline-warning" data-bs-toggle="modal" data-bs-target="#exampleModal">Edit</button>
        
         <button type="button" class="btn btn-outline-info">Postpone</button>
         <button type="button" class="btn btn-outline-danger">Delete</button>
         </div>



</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        @Html.Partial("_EditTask")
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

TODOList/Views/Day/DoneTask.cshtml
@model TODOList.Models.TaskModel

<div class="alert alert-dismissible alert-success">
    <div class="card-header">
         <legend>@Html.DisplayFor(model => model.Name)</legend>
         @Html.DisplayFor(model => model.StartTime) : @Html.DisplayFor(model => model.EndTime) &emsp;
         @Html.DisplayNameFor(model => model.Priority):  @Html.DisplayFor(model => model.Priority) &emsp;     
         
         @Html.DisplayFor(model=>model.IsDone)
            <label>
 
                @Html.DisplayNameFor(model => model.IsDone)
             </label> &emsp;

        
           <br> <br>
          

         <br>
         @Html.DisplayFor(model => model.Description)

         <br><br>

    </div>


</div>

TODOList/Views/Day/Index.cshtml
@model IEnumerable<TODOList.Models.DayModel>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th class="ToReset">
                Do zrobienia Dziś
            </th>
        </tr>

              

    </thead>

    <tbody >
        @foreach (var item in Model) {
        
        <tr class="navbar navbar-expand-lg navbar-light bg-light">
            <td class="ToReset">
               <h1> @Html.DisplayFor(modelItem => item.Date.DayOfWeek) </h1>
                <div id="zadanie">
                    @if(item.Tasks != null)
                    {
                        @foreach(var taskItem in item.Tasks)
                        {   <div class="taskPageDiv" id="@taskItem.Id">
                            @if(taskItem.IsDone == true)
                            {
                                  @Html.Partial("DoneTask",taskItem)  
                            }
                            else
                                @Html.Partial("DetailsTask",taskItem)

                            
                            
                            </div>
                            <div style= margin:10px ></div>
                            
                        }    
                    }                       
                </div>

                <button type="button" class="btn btn-info">Add task</button>

            </td>
        </tr>
} 
    </tbody>
</table>

TODOList/Views/Day/_EditTask.cshtml
@model TODOList.Models.TaskModel

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="_EditTask">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsDone" /> @Html.DisplayNameFor(model => model.IsDone)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Priority" class="control-label"></label>
                <input asp-for="Priority" class="form-control" />
                <span asp-validation-for="Priority" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Regularity" /> @Html.DisplayNameFor(model => model.Regularity)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="StartTime" class="control-label"></label>
                <input asp-for="StartTime" class="form-control" />
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndTime" class="control-label"></label>
                <input asp-for="EndTime" class="form-control" />
                <span asp-validation-for="EndTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </form>
    </div>
</div>

TODOList/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TODOList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TODOList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TODOList.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TODOList</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TODOList - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>